Beans-BV/dotnet-stellar-sdk

.github/workflows/publish_nuget.yml, nugetreadme.md, stellar-dotnet-sdk-test/NetworkTest.cs, stellar-dotnet-sdk/SorobanTransactionData.cs, stellar-dotnet-sdk/stellar-dotnet-sdk.csproj
=> Update nuget settings

.github/workflows/publish_nuget.yml, stellar-dotnet-sdk-console/stellar-dotnet-sdk-console.csproj, stellar-dotnet-sdk-xdr/stellar-dotnet-sdk-xdr.csproj
Updated setting so a build runs on a push to a PR.
=> Disabled packing for console and xdr projects

stellar-dotnet-sdk-console/Program.cs, stellar-dotnet-sdk/Server.cs, stellar-dotnet-sdk/UriBuilderExtensions.cs, stellar-dotnet-sdk/requests/RequestBuilder.cs
=> Updated the request builder to maintain the original path and query

StellarDotnetSdk.Tests/WebAuthenticationTest.cs, StellarDotnetSdk/WebAuthentication.cs
The default value of the now added a grace period to it which can cause failing SEP-10 validations.
I changed the default value of the now parameter to `DateTimeOffset.Now` and I move the grace logic to the validate time bounds method.
`WebAuthentication.BuildChallengeTransaction`:
- Argument `now` rename to `validFrom`
- Argument `timeout` renamed to `validFor`
`WebAuthentication.ReadChallengeTransaction`:
- Argument `now` default value change: `DateTimeOffset.Now.AddSeconds(GracePeriod)` -> `DateTimeOffset.Now`
=> Fixed SEP-10 web auth issue

StellarDotnetSdk.Tests/ScValTest.cs, StellarDotnetSdk.Tests/SorobanServerTest.cs, StellarDotnetSdk/Requests/DefaultHttpClient.cs, StellarDotnetSdk/Requests/DefaultStellarSdkHttpClient.cs, StellarDotnetSdk/Requests/SorobanRpc/GetTransactionsRequest.cs, StellarDotnetSdk/Requests/SorobanRpc/PaginationOptions.cs, StellarDotnetSdk/Responses/SorobanRpc/TransactionInfo.cs, StellarDotnetSdk/Server.cs, StellarDotnetSdk/Soroban/SCVal.cs, StellarDotnetSdk/Soroban/SorobanServer.cs, StellarDotnetSdk/StellarDotnetSdk.csproj
- Added unit tests for `GetLedgerEntries` of type `ConfigSetting` and `TTL`.
- Added new `SCInt128` constructor that accepts a numeric string.
- Update `SorobanServer` constructor `SorobanServer(string uri)` to `SorobanServer(string uri, string? bearerToken = null)`, allowing direct injection of custom bearer tokens.
- Reorder parameters in `SCInt128` constructor, from `SCInt128(ulong lo, long hi)` to `SCInt128(long hi, ulong lo)` to match with other SDKs.
=> Soroban improvements

StellarDotnetSdk.Tests/LedgerKeyTest.cs, StellarDotnetSdk.Tests/Operations/OperationTest.cs, StellarDotnetSdk.Tests/SorobanServerTest.cs, StellarDotnetSdk/LedgerKeys/LedgerKey.cs, StellarDotnetSdk/LedgerKeys/LedgerKeyClaimableBalance.cs, StellarDotnetSdk/Operations/ClaimClaimableBalanceOperation.cs, StellarDotnetSdk/Operations/RevokeLedgerEntrySponsorshipOperation.cs
Add `LedgerKeyClaimableBalance` constructor that accepts a string
=> Add LedgerKeyClaimableBalance constructor that accepts a string

.github/workflows/publish_nuget.yml
Add ability to publish pre-release Nuget packages
=> Add ability to publish pre-release Nuget packages

StellarDotnetSdk.Tests/SorobanServerTest.cs, StellarDotnetSdk/Responses/SorobanRpc/GetVersionInfoResponse.cs
Fix getVersionInfoResponse json name typo
=> Fix getVersionInfoResponse json name typo

StellarDotnetSdk.Tests/Responses/Effects/EffectDeserializerTest.cs, StellarDotnetSdk.Tests/Responses/PathsPageDeserializerTest.cs, StellarDotnetSdk.Tests/SponsorshipTest.cs, StellarDotnetSdk.Tests/StellarDotnetSdk.Tests.csproj, StellarDotnetSdk.Tests/TestData/Responses/Effects/effectTradeAlphaNum12Native.json, StellarDotnetSdk.Tests/TestData/Responses/Effects/effectTradeNativeAphaNum4.json, StellarDotnetSdk.Tests/TestData/Responses/pathPage.json, StellarDotnetSdk/Responses/Effects/TradeEffectResponse.cs, StellarDotnetSdk/Responses/PathResponse.cs, StellarDotnetSdk/StellarDotnetSdk.csproj
Update Asset property in `PathResponse` and `TradeEffectResponse` to support native asset.
=> Update Asset property in some responses to support native asset

StellarDotnetSdk.Tests/SorobanServerTest.cs, StellarDotnetSdk/Soroban/SorobanServer.cs
=> feature: support sending FeeBump transactions in SorobanServer

.github/workflows/publish_nuget.yml
=> Bump version for artifact actions

Examples/Horizon/StellarDotnetSdk.Examples.Horizon.csproj, Examples/Soroban/StellarDotnetSdk.Examples.Soroban.csproj
=> Add required csproj properties for example projects

.github/workflows/update-documentation.yml
=> Specify .NET version for building docs action

global.json
=> Update .NET SDK version in global.json

StellarDotnetSdk.Console/StellarDotnetSdk.Console.csproj, StellarDotnetSdk.Tests/StellarDotnetSdk.Tests.csproj, StellarDotnetSdk.Tests/WebAuthenticationTest.cs, StellarDotnetSdk/StellarDotnetSdk.csproj, StellarDotnetSdk/WebAuthentication.cs
WebAuthencation improvements:
- Better naming and extracted helper methods for clearer logic flow and better readability
- Removed unnecessary operations and improved variable usage for improved performance
- Replaced obsoleted `RandomGenerator` with recommended `RandomNumberGenerator`
=> Improve WebAuthentication

StellarDotnetSdk.Tests/SorobanServerTest.cs, StellarDotnetSdk.Tests/Transactions/TransactionTest.cs, StellarDotnetSdk/Soroban/SorobanResources.cs
=> refactor: rename SorobanResources.ReadBytes to DiskReadBytes

StellarDotnetSdk.Tests/ServerTest.cs, StellarDotnetSdk/Responses/SubmitTransactionAsyncResponse.cs
=> feat: update SubmitTransactionAsyncResponse

StellarDotnetSdk.Tests/LedgerEntryChangeTest.cs, StellarDotnetSdk/LedgerEntries/LedgerEntryChange.cs, StellarDotnetSdk/LedgerEntries/LedgerEntryRestored.cs
=> feat: update LedgerEntryChange

StellarDotnetSdk.Tests/AddressTest.cs, StellarDotnetSdk/Operations/InvokeHostFunctionOperation.cs, StellarDotnetSdk/Soroban/SCVal.cs
=> feat: add new variants of ScAddress - muxed account, liquidity pool and claimable balance

StellarDotnetSdk/Requests/OperationsRequestBuilder.cs
=> fix: OperationsRequestBuilder#ForClaimableBalance

Examples/Horizon/HorizonExamples.cs, StellarDotnetSdk/Responses/SorobanRpc/TransactionInfo.cs
=> fix: update examples to support Protocol 23
